consistency

diff --git a/.local/bin/tidy-obsidian b/.local/bin/tidy-obsidian
--- a/.local/bin/tidy-obsidian
+++ b/.local/bin/tidy-obsidian
@@ -1,13 +1,13 @@
 #!/bin/bash
 set -Eeuo pipefail
-trap 'echo "$0: Error on line ${LINENO}: ${BASH_COMMAND}" >&2' ERR
+trap 'echo "${0}: Error on line ${LINENO}: ${BASH_COMMAND}" >&2' ERR
 
 if [ -z "${1-}" ]; then
 	echo 'No argument supplied' >&2
 	exit 1
 fi
 
-VAULT="$1"
+VAULT="${1}"
 
 if [ ! -d "${VAULT}" ]; then
 	echo "'${VAULT}' is not a directory" >&2
